# Generated by Django 3.2.6 on 2023-10-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('viewed_by_recruiter', 'Viewed_by_recruiter'), ('shortlisted', 'Shortlisted'), ('not shortlisted', 'Not shortlisted'), ('awaiting for response', 'Awaiting for response'), ('selected', 'Selected'), ('not selected', 'Not selected')], max_length=100),
        ),
    ]
